/**
 * setup-local-env.ts — interactive prompt to create .env.local with required secrets.
 * Does NOT echo secret values to the console.
 * Usage: pnpm env:setup
 */

import { createInterface } from "node:readline";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ENV_PATH = resolve(process.cwd(), ".env.local");

const VARS = [
  {
    key: "DATABASE_URL",
    hint: "Supabase pooler URI (port 6543, pgBouncer)",
    required: true,
  },
  {
    key: "DIRECT_URL",
    hint: "Supabase direct URI (port 5432)",
    required: true,
  },
  {
    key: "SESSION_SECRET",
    hint: "Random >=32 chars (openssl rand -hex 32)",
    required: true,
  },
  {
    key: "CRON_SECRET",
    hint: "Protects /api/cron/* endpoints",
    required: false,
  },
  {
    key: "KIOSK_TOKEN",
    hint: "Kiosk write-access token",
    required: false,
  },
] as const;

async function main() {
  console.log("🔧 InternalToolKit — Local Env Setup");
  console.log("=====================================");
  console.log(`Target file: ${ENV_PATH}`);
  console.log("⚠️  Values will NOT be echoed to the console.\n");

  // Load existing .env.local if present
  let existing: Record<string, string> = {};
  if (existsSync(ENV_PATH)) {
    const lines = readFileSync(ENV_PATH, "utf-8").split("\n");
    for (const line of lines) {
      const match = line.match(/^([A-Z_]+)=(.*)$/);
      if (match?.[1]) existing[match[1]] = match[2] ?? "";
    }
  }

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> =>
    new Promise((res) => rl.question(q, (a) => res(a.trim())));

  const entries: [string, string][] = [];

  for (const v of VARS) {
    const tag = v.required ? "[REQUIRED]" : "[optional]";
    const current = existing[v.key];

    if (current) {
      const skip = await ask(
        `${tag} ${v.key} already set. Overwrite? (y/N): `,
      );
      if (skip.toLowerCase() !== "y") {
        entries.push([v.key, current]);
        continue;
      }
    }

    const val = await ask(`${tag} ${v.key} (${v.hint}): `);

    if (!val && v.required) {
      console.warn(`   ⚠️  ${v.key} left empty — you must fill it in manually.`);
    }

    entries.push([v.key, val ? `"${val}"` : '""']);
  }

  rl.close();

  // Preserve non-secret lines from existing file
  const preserveKeys = new Set(entries.map(([k]) => k));
  const preserved: string[] = [];
  if (existsSync(ENV_PATH)) {
    for (const line of readFileSync(ENV_PATH, "utf-8").split("\n")) {
      const match = line.match(/^([A-Z_]+)=/);
      if (match?.[1] && preserveKeys.has(match[1])) continue;
      preserved.push(line);
    }
  }

  const output = [
    "# Auto-generated by setup-local-env.ts — DO NOT COMMIT",
    ...entries.map(([k, v]) => `${k}=${v}`),
    "",
    ...preserved.filter((l) => l.trim()),
    "",
  ].join("\n");

  writeFileSync(ENV_PATH, output, "utf-8");
  console.log(`\n✅ Saved ${ENV_PATH}`);
  console.log("Run 'pnpm env:check' to verify.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
